// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Login(Api)
通用授权模块


    Schemes:
      http
    Host: virtserver.swaggerhub.com
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
