// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Passport/models"
)

// UserUpdateProfileOKCode is the HTTP code returned for type UserUpdateProfileOK
const UserUpdateProfileOKCode int = 200

/*UserUpdateProfileOK 修改成功，返回成功信息

swagger:response userUpdateProfileOK
*/
type UserUpdateProfileOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserState `json:"body,omitempty"`
}

// NewUserUpdateProfileOK creates UserUpdateProfileOK with default headers values
func NewUserUpdateProfileOK() *UserUpdateProfileOK {
	return &UserUpdateProfileOK{}
}

// WithPayload adds the payload to the user update profile o k response
func (o *UserUpdateProfileOK) WithPayload(payload *models.UserState) *UserUpdateProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user update profile o k response
func (o *UserUpdateProfileOK) SetPayload(payload *models.UserState) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserUpdateProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserUpdateProfileDefault error

swagger:response userUpdateProfileDefault
*/
type NrUserUpdateProfileDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserUpdateProfileDefault creates NrUserUpdateProfileDefault with default headers values
func NewNrUserUpdateProfileDefault(code int) *NrUserUpdateProfileDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserUpdateProfileDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user update profile default response
func (o *NrUserUpdateProfileDefault) WithStatusCode(code int) *NrUserUpdateProfileDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user update profile default response
func (o *NrUserUpdateProfileDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user update profile default response
func (o *NrUserUpdateProfileDefault) WithPayload(payload *models.Error) *NrUserUpdateProfileDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user update profile default response
func (o *NrUserUpdateProfileDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserUpdateProfileDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
