// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Passport/models"
)

// UserUpdateAvatarOKCode is the HTTP code returned for type UserUpdateAvatarOK
const UserUpdateAvatarOKCode int = 200

/*UserUpdateAvatarOK 修改成功，返回成功信息

swagger:response userUpdateAvatarOK
*/
type UserUpdateAvatarOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserUpdateAvatarOKBody `json:"body,omitempty"`
}

// NewUserUpdateAvatarOK creates UserUpdateAvatarOK with default headers values
func NewUserUpdateAvatarOK() *UserUpdateAvatarOK {
	return &UserUpdateAvatarOK{}
}

// WithPayload adds the payload to the user update avatar o k response
func (o *UserUpdateAvatarOK) WithPayload(payload *models.UserUpdateAvatarOKBody) *UserUpdateAvatarOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user update avatar o k response
func (o *UserUpdateAvatarOK) SetPayload(payload *models.UserUpdateAvatarOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserUpdateAvatarOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserUpdateAvatarDefault 返回错误

swagger:response userUpdateAvatarDefault
*/
type NrUserUpdateAvatarDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserUpdateAvatarDefault creates NrUserUpdateAvatarDefault with default headers values
func NewNrUserUpdateAvatarDefault(code int) *NrUserUpdateAvatarDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserUpdateAvatarDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user update avatar default response
func (o *NrUserUpdateAvatarDefault) WithStatusCode(code int) *NrUserUpdateAvatarDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user update avatar default response
func (o *NrUserUpdateAvatarDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user update avatar default response
func (o *NrUserUpdateAvatarDefault) WithPayload(payload *models.Error) *NrUserUpdateAvatarDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user update avatar default response
func (o *NrUserUpdateAvatarDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserUpdateAvatarDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
