// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrUserUpdateAvatarHandlerFunc turns a function with the right signature into a user update avatar handler
type NrUserUpdateAvatarHandlerFunc func(NrUserUpdateAvatarParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrUserUpdateAvatarHandlerFunc) Handle(params NrUserUpdateAvatarParams) middleware.Responder {
	return fn(params)
}

// NrUserUpdateAvatarHandler interface for that can handle valid user update avatar params
type NrUserUpdateAvatarHandler interface {
	Handle(NrUserUpdateAvatarParams) middleware.Responder
}

// NewNrUserUpdateAvatar creates a new http.Handler for the user update avatar operation
func NewNrUserUpdateAvatar(ctx *middleware.Context, handler NrUserUpdateAvatarHandler) *NrUserUpdateAvatar {
	return &NrUserUpdateAvatar{Context: ctx, Handler: handler}
}

/*NrUserUpdateAvatar swagger:route POST /user/updateAvatar User userUpdateAvatar

修改头像API

*/
type NrUserUpdateAvatar struct {
	Context *middleware.Context
	Handler NrUserUpdateAvatarHandler
}

func (o *NrUserUpdateAvatar) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrUserUpdateAvatarParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
