// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Login/models"
)

// UserGetOwnerAccountOKCode is the HTTP code returned for type UserGetOwnerAccountOK
const UserGetOwnerAccountOKCode int = 200

/*UserGetOwnerAccountOK 返回成功信息

swagger:response userGetOwnerAccountOK
*/
type UserGetOwnerAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.AccountState `json:"body,omitempty"`
}

// NewUserGetOwnerAccountOK creates UserGetOwnerAccountOK with default headers values
func NewUserGetOwnerAccountOK() *UserGetOwnerAccountOK {
	return &UserGetOwnerAccountOK{}
}

// WithPayload adds the payload to the user get owner account o k response
func (o *UserGetOwnerAccountOK) WithPayload(payload *models.AccountState) *UserGetOwnerAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user get owner account o k response
func (o *UserGetOwnerAccountOK) SetPayload(payload *models.AccountState) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserGetOwnerAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserGetOwnerAccountDefault 返回错误

swagger:response userGetOwnerAccountDefault
*/
type NrUserGetOwnerAccountDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserGetOwnerAccountDefault creates NrUserGetOwnerAccountDefault with default headers values
func NewNrUserGetOwnerAccountDefault(code int) *NrUserGetOwnerAccountDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserGetOwnerAccountDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user get owner account default response
func (o *NrUserGetOwnerAccountDefault) WithStatusCode(code int) *NrUserGetOwnerAccountDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user get owner account default response
func (o *NrUserGetOwnerAccountDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user get owner account default response
func (o *NrUserGetOwnerAccountDefault) WithPayload(payload *models.Error) *NrUserGetOwnerAccountDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user get owner account default response
func (o *NrUserGetOwnerAccountDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserGetOwnerAccountDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
