// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrUserUpdateProfileHandlerFunc turns a function with the right signature into a user update profile handler
type NrUserUpdateProfileHandlerFunc func(NrUserUpdateProfileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrUserUpdateProfileHandlerFunc) Handle(params NrUserUpdateProfileParams) middleware.Responder {
	return fn(params)
}

// NrUserUpdateProfileHandler interface for that can handle valid user update profile params
type NrUserUpdateProfileHandler interface {
	Handle(NrUserUpdateProfileParams) middleware.Responder
}

// NewNrUserUpdateProfile creates a new http.Handler for the user update profile operation
func NewNrUserUpdateProfile(ctx *middleware.Context, handler NrUserUpdateProfileHandler) *NrUserUpdateProfile {
	return &NrUserUpdateProfile{Context: ctx, Handler: handler}
}

/*NrUserUpdateProfile swagger:route POST /user/updateProfile User userUpdateProfile

修改用户资料接口

修改用户资料接口

*/
type NrUserUpdateProfile struct {
	Context *middleware.Context
	Handler NrUserUpdateProfileHandler
}

func (o *NrUserUpdateProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrUserUpdateProfileParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
