// Code generated by go-swagger; DO NOT EDIT.

package passport

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"Passport/models"
)

// NewNrPassportSendSmsParams creates a new NrPassportSendSmsParams object
// with the default values initialized.
func NewNrPassportSendSmsParams() NrPassportSendSmsParams {
	var ()
	return NrPassportSendSmsParams{}
}

// NrPassportSendSmsParams contains all the bound params for the passport send sms operation
// typically these are obtained from a http.Request
//
// swagger:parameters /passport/sendSms
type NrPassportSendSmsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*下发短信验证码请求JSON
	  In: body
	*/
	Body *models.PassportSendSmsParamsBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *NrPassportSendSmsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PassportSendSmsParamsBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
