// Code generated by go-swagger; DO NOT EDIT.

package passport

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"Passport/models"
)

// NewNrPassportBindMobileParams creates a new NrPassportBindMobileParams object
// with the default values initialized.
func NewNrPassportBindMobileParams() NrPassportBindMobileParams {
	var ()
	return NrPassportBindMobileParams{}
}

// NrPassportBindMobileParams contains all the bound params for the passport bind mobile operation
// typically these are obtained from a http.Request
//
// swagger:parameters /passport/bindMobile
type NrPassportBindMobileParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*绑定手机号JSON
	  In: body
	*/
	Body *models.PassportBindMobileParamsBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *NrPassportBindMobileParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PassportBindMobileParamsBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
