// Code generated by go-swagger; DO NOT EDIT.

package passport

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrPassportLoginByThirdPartyHandlerFunc turns a function with the right signature into a passport login by third party handler
type NrPassportLoginByThirdPartyHandlerFunc func(NrPassportLoginByThirdPartyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrPassportLoginByThirdPartyHandlerFunc) Handle(params NrPassportLoginByThirdPartyParams) middleware.Responder {
	return fn(params)
}

// NrPassportLoginByThirdPartyHandler interface for that can handle valid passport login by third party params
type NrPassportLoginByThirdPartyHandler interface {
	Handle(NrPassportLoginByThirdPartyParams) middleware.Responder
}

// NewNrPassportLoginByThirdParty creates a new http.Handler for the passport login by third party operation
func NewNrPassportLoginByThirdParty(ctx *middleware.Context, handler NrPassportLoginByThirdPartyHandler) *NrPassportLoginByThirdParty {
	return &NrPassportLoginByThirdParty{Context: ctx, Handler: handler}
}

/*NrPassportLoginByThirdParty swagger:route POST /passport/loginByThirdParty Passport passportLoginByThirdParty

第三方登录

第三方登录

*/
type NrPassportLoginByThirdParty struct {
	Context *middleware.Context
	Handler NrPassportLoginByThirdPartyHandler
}

func (o *NrPassportLoginByThirdParty) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrPassportLoginByThirdPartyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
