// Code generated by go-swagger; DO NOT EDIT.

package passport

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Login/models"
)

// PassportSendSmsOKCode is the HTTP code returned for type PassportSendSmsOK
const PassportSendSmsOKCode int = 200

/*PassportSendSmsOK 验证码发送成功

swagger:response passportSendSmsOK
*/
type PassportSendSmsOK struct {

	/*
	  In: Body
	*/
	Payload *models.State `json:"body,omitempty"`
}

// NewPassportSendSmsOK creates PassportSendSmsOK with default headers values
func NewPassportSendSmsOK() *PassportSendSmsOK {
	return &PassportSendSmsOK{}
}

// WithPayload adds the payload to the passport send sms o k response
func (o *PassportSendSmsOK) WithPayload(payload *models.State) *PassportSendSmsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the passport send sms o k response
func (o *PassportSendSmsOK) SetPayload(payload *models.State) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PassportSendSmsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrPassportSendSmsDefault error

swagger:response passportSendSmsDefault
*/
type NrPassportSendSmsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrPassportSendSmsDefault creates NrPassportSendSmsDefault with default headers values
func NewNrPassportSendSmsDefault(code int) *NrPassportSendSmsDefault {
	if code <= 0 {
		code = 500
	}

	return &NrPassportSendSmsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the passport send sms default response
func (o *NrPassportSendSmsDefault) WithStatusCode(code int) *NrPassportSendSmsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the passport send sms default response
func (o *NrPassportSendSmsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the passport send sms default response
func (o *NrPassportSendSmsDefault) WithPayload(payload *models.Error) *NrPassportSendSmsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the passport send sms default response
func (o *NrPassportSendSmsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrPassportSendSmsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
