// Code generated by go-swagger; DO NOT EDIT.

package passport

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Login/models"
)

// PassportQuickLoginOKCode is the HTTP code returned for type PassportQuickLoginOK
const PassportQuickLoginOKCode int = 200

/*PassportQuickLoginOK 登录成功，返回登录信息

swagger:response passportQuickLoginOK
*/
type PassportQuickLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.LoginState `json:"body,omitempty"`
}

// NewPassportQuickLoginOK creates PassportQuickLoginOK with default headers values
func NewPassportQuickLoginOK() *PassportQuickLoginOK {
	return &PassportQuickLoginOK{}
}

// WithPayload adds the payload to the passport quick login o k response
func (o *PassportQuickLoginOK) WithPayload(payload *models.LoginState) *PassportQuickLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the passport quick login o k response
func (o *PassportQuickLoginOK) SetPayload(payload *models.LoginState) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PassportQuickLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrPassportQuickLoginDefault error

swagger:response passportQuickLoginDefault
*/
type NrPassportQuickLoginDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrPassportQuickLoginDefault creates NrPassportQuickLoginDefault with default headers values
func NewNrPassportQuickLoginDefault(code int) *NrPassportQuickLoginDefault {
	if code <= 0 {
		code = 500
	}

	return &NrPassportQuickLoginDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the passport quick login default response
func (o *NrPassportQuickLoginDefault) WithStatusCode(code int) *NrPassportQuickLoginDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the passport quick login default response
func (o *NrPassportQuickLoginDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the passport quick login default response
func (o *NrPassportQuickLoginDefault) WithPayload(payload *models.Error) *NrPassportQuickLoginDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the passport quick login default response
func (o *NrPassportQuickLoginDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrPassportQuickLoginDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
