// Code generated by go-swagger; DO NOT EDIT.

package passport

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Passport/models"
)

// PassportGetbackPwdOKCode is the HTTP code returned for type PassportGetbackPwdOK
const PassportGetbackPwdOKCode int = 200

/*PassportGetbackPwdOK 返回成功信息

swagger:response passportGetbackPwdOK
*/
type PassportGetbackPwdOK struct {

	/*
	  In: Body
	*/
	Payload *models.State `json:"body,omitempty"`
}

// NewPassportGetbackPwdOK creates PassportGetbackPwdOK with default headers values
func NewPassportGetbackPwdOK() *PassportGetbackPwdOK {
	return &PassportGetbackPwdOK{}
}

// WithPayload adds the payload to the passport getback pwd o k response
func (o *PassportGetbackPwdOK) WithPayload(payload *models.State) *PassportGetbackPwdOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the passport getback pwd o k response
func (o *PassportGetbackPwdOK) SetPayload(payload *models.State) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PassportGetbackPwdOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrPassportGetbackPwdDefault error

swagger:response passportGetbackPwdDefault
*/
type NrPassportGetbackPwdDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrPassportGetbackPwdDefault creates NrPassportGetbackPwdDefault with default headers values
func NewNrPassportGetbackPwdDefault(code int) *NrPassportGetbackPwdDefault {
	if code <= 0 {
		code = 500
	}

	return &NrPassportGetbackPwdDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the passport getback pwd default response
func (o *NrPassportGetbackPwdDefault) WithStatusCode(code int) *NrPassportGetbackPwdDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the passport getback pwd default response
func (o *NrPassportGetbackPwdDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the passport getback pwd default response
func (o *NrPassportGetbackPwdDefault) WithPayload(payload *models.Error) *NrPassportGetbackPwdDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the passport getback pwd default response
func (o *NrPassportGetbackPwdDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrPassportGetbackPwdDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
