// Code generated by go-swagger; DO NOT EDIT.

package passport

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	_"github.com/jinzhu/gorm/dialects/mysql"
	"github.com/go-openapi/runtime/middleware"
	"Passport/models"
	"Passport/utils"
	"fmt"
	"time"
)

// NrPassportBindMobileHandlerFunc turns a function with the right signature into a passport bind mobile handler
type NrPassportBindMobileHandlerFunc func(NrPassportBindMobileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrPassportBindMobileHandlerFunc) Handle(params NrPassportBindMobileParams) middleware.Responder {
	return fn(params)
}

// NrPassportBindMobileHandler interface for that can handle valid passport bind mobile params
type NrPassportBindMobileHandler interface {
	Handle(NrPassportBindMobileParams) middleware.Responder
}

// NewNrPassportBindMobile creates a new http.Handler for the passport bind mobile operation
func NewNrPassportBindMobile(ctx *middleware.Context, handler NrPassportBindMobileHandler) *NrPassportBindMobile {
	return &NrPassportBindMobile{Context: ctx, Handler: handler}
}

/*NrPassportBindMobile swagger:route POST /passport/bindMobile Passport passportBindMobile

绑定手机号接口

绑定手机号接口

*/
type NrPassportBindMobile struct {
	Context *middleware.Context
	Handler NrPassportBindMobileHandler
}

func (o *NrPassportBindMobile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrPassportBindMobileParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	//res := o.Handler.Handle(Params) // actually handle the request

	db, err := utils.OpenConnection()
	if err != nil {
		fmt.Println(err.Error())
	}
	defer db.Close()

	var res models.RespState
	var state models.State

	var user models.UserBase
	var sms SMSRecord

	// 定义错误信息
	var code int64
	var message string

	// 先判断验证码是否正确
	db.Table(utils.T_SMS).Where("phone=?", *Params.Body.Phone).Where("code=?", *Params.Body.ValidCode).Where("type=2").Order("create_at DESC").First(&sms)
	if len(sms.Code) == 0 {
		code = 401
		message = "验证码不正确"
	} else {
		if time.Now().Unix() - utils.T_EXPIRED_SECONDS > sms.CreateAt {
			code = 402
			message = "验证码已失效"
		} else {

			db.Table(utils.T_USER).Where("id=?", utils.DecodeUserID(*Params.Body.Euid)).Where("status=0").Find(&user)
			if user.ID == 0 {
				code = 403
				message = "用户不存在"
			} else {
				sql := "UPDATE btk_User SET phone = ? WHERE euid = ? AND status = 0"
				db.Exec(sql, *Params.Body.Phone, *Params.Body.Euid)
				code = 200
				message = "修改成功"
			}
		}
	}

	state.UnmarshalBinary([]byte(utils.Response200(code, message)))
	res.State = &state

	o.Context.Respond(rw, r, route.Produces, route, res)

}
