// Code generated by go-swagger; DO NOT EDIT.

package passport

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Passport/models"
)

// PassportRegisterOKCode is the HTTP code returned for type PassportRegisterOK
const PassportRegisterOKCode int = 200

/*PassportRegisterOK 注册成功，返回注册成功信息

swagger:response passportRegisterOK
*/
type PassportRegisterOK struct {

	/*
	  In: Body
	*/
	Payload *models.RegisterState `json:"body,omitempty"`
}

// NewPassportRegisterOK creates PassportRegisterOK with default headers values
func NewPassportRegisterOK() *PassportRegisterOK {
	return &PassportRegisterOK{}
}

// WithPayload adds the payload to the passport register o k response
func (o *PassportRegisterOK) WithPayload(payload *models.RegisterState) *PassportRegisterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the passport register o k response
func (o *PassportRegisterOK) SetPayload(payload *models.RegisterState) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PassportRegisterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrPassportRegisterDefault error

swagger:response passportRegisterDefault
*/
type NrPassportRegisterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrPassportRegisterDefault creates NrPassportRegisterDefault with default headers values
func NewNrPassportRegisterDefault(code int) *NrPassportRegisterDefault {
	if code <= 0 {
		code = 500
	}

	return &NrPassportRegisterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the passport register default response
func (o *NrPassportRegisterDefault) WithStatusCode(code int) *NrPassportRegisterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the passport register default response
func (o *NrPassportRegisterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the passport register default response
func (o *NrPassportRegisterDefault) WithPayload(payload *models.Error) *NrPassportRegisterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the passport register default response
func (o *NrPassportRegisterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrPassportRegisterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
