// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PassportRegisterParamsBody passport register params body
// swagger:model passportRegisterParamsBody
type PassportRegisterParamsBody struct {

	// 生日(格式必须为:yyyy-MM-dd)
	BirthDay string `json:"birth_day,omitempty"`

	// 客户端类型
	Client string `json:"client,omitempty"`

	// 用户性别 (0:保密 1:男 2:女)
	Gender int64 `json:"gender,omitempty"`

	// 唯一识别号
	Imei string `json:"imei,omitempty"`

	// 邀请码
	InviteCode string `json:"invite_code,omitempty"`

	// 用户昵称，最大11个字符
	NickName string `json:"nick_name,omitempty"`

	// 注册密码
	// Required: true
	Password *string `json:"password"`

	// 注册手机号
	// Required: true
	Phone *string `json:"phone"`

	// 时间戳(加密串要用到,供服务端验证，简单防刷)
	Ts int64 `json:"ts,omitempty"`

	// 加密串
	Val string `json:"val,omitempty"`

	// 手机验证码，快捷登录方式可用
	// Required: true
	ValidCode *string `json:"valid_code"`

	// 版本号
	Version string `json:"version,omitempty"`
}

// Validate validates this passport register params body
func (m *PassportRegisterParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePassword(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePhone(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateValidCode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PassportRegisterParamsBody) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

func (m *PassportRegisterParamsBody) validatePhone(formats strfmt.Registry) error {

	if err := validate.Required("phone", "body", m.Phone); err != nil {
		return err
	}

	return nil
}

func (m *PassportRegisterParamsBody) validateValidCode(formats strfmt.Registry) error {

	if err := validate.Required("valid_code", "body", m.ValidCode); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PassportRegisterParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PassportRegisterParamsBody) UnmarshalBinary(b []byte) error {
	var res PassportRegisterParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
