// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PassportLoginByThirdPartyParamsBody passport login by third party params body
// swagger:model passportLoginByThirdPartyParamsBody
type PassportLoginByThirdPartyParamsBody struct {

	// 第三方平台用户头像
	Avatar string `json:"avatar,omitempty"`

	// 客户端类型
	Client string `json:"client,omitempty"`

	// 唯一识别号
	Imei string `json:"imei,omitempty"`

	// 第三方平台用户用户名
	Name string `json:"name,omitempty"`

	// 开放平台唯一ID
	// Required: true
	OpenID *string `json:"open_id"`

	// 第三方登录平台，当type=3时，需要传入platform来判断从哪个平台登入
	Platform string `json:"platform,omitempty"`

	// 时间戳(加密串要用到,供服务端验证，简单防刷)
	Ts int64 `json:"ts,omitempty"`

	// 第三方登录方式 0=微信,1=QQ,2=微博,3=其他
	// Required: true
	Type *int64 `json:"type"`

	// 加密串
	Val string `json:"val,omitempty"`

	// 版本号
	Version string `json:"version,omitempty"`
}

// Validate validates this passport login by third party params body
func (m *PassportLoginByThirdPartyParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOpenID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PassportLoginByThirdPartyParamsBody) validateOpenID(formats strfmt.Registry) error {

	if err := validate.Required("open_id", "body", m.OpenID); err != nil {
		return err
	}

	return nil
}

func (m *PassportLoginByThirdPartyParamsBody) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PassportLoginByThirdPartyParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PassportLoginByThirdPartyParamsBody) UnmarshalBinary(b []byte) error {
	var res PassportLoginByThirdPartyParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
