// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PassportSendSmsParamsBody passport send sms params body
// swagger:model passportSendSmsParamsBody
type PassportSendSmsParamsBody struct {

	// 客户端类型
	Client string `json:"client,omitempty"`

	// 唯一识别号
	Imei string `json:"imei,omitempty"`

	// 手机号
	// Required: true
	Phone *string `json:"phone"`

	// 时间戳(加密串要用到,供服务端验证，简单防刷)
	Ts int64 `json:"ts,omitempty"`

	// 下发验证码的方式(0:注册 1:快捷登录 2:绑定手机号 3:找回密码)
	Type int64 `json:"type,omitempty"`

	// 加密串
	Val string `json:"val,omitempty"`

	// 版本号
	Version string `json:"version,omitempty"`
}

// Validate validates this passport send sms params body
func (m *PassportSendSmsParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePhone(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PassportSendSmsParamsBody) validatePhone(formats strfmt.Registry) error {

	if err := validate.Required("phone", "body", m.Phone); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PassportSendSmsParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PassportSendSmsParamsBody) UnmarshalBinary(b []byte) error {
	var res PassportSendSmsParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
