// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserUpdateAvatarParamsBody user update avatar params body
// swagger:model userUpdateAvatarParamsBody
type UserUpdateAvatarParamsBody struct {

	// 上传的头像图片地址
	// Required: true
	Avatar *string `json:"avatar"`

	// 客户端类型
	Client string `json:"client,omitempty"`

	// 创建人ID
	// Required: true
	Euid *string `json:"euid"`

	// 唯一识别号
	Imei string `json:"imei,omitempty"`

	// 时间戳(加密串要用到,供服务端验证，简单防刷)
	Ts int64 `json:"ts,omitempty"`

	// 加密串
	Val string `json:"val,omitempty"`

	// 版本号
	Version string `json:"version,omitempty"`
}

// Validate validates this user update avatar params body
func (m *UserUpdateAvatarParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvatar(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateEuid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserUpdateAvatarParamsBody) validateAvatar(formats strfmt.Registry) error {

	if err := validate.Required("avatar", "body", m.Avatar); err != nil {
		return err
	}

	return nil
}

func (m *UserUpdateAvatarParamsBody) validateEuid(formats strfmt.Registry) error {

	if err := validate.Required("euid", "body", m.Euid); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserUpdateAvatarParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUpdateAvatarParamsBody) UnmarshalBinary(b []byte) error {
	var res UserUpdateAvatarParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
