// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserInfo 返回的用户信息
// swagger:model UserInfo
type UserInfo struct {

	// 用户头像
	Avatar string `json:"avatar,omitempty"`

	// 生日(格式为:yyyy-MM-dd)
	BirthDay string `json:"birth_day,omitempty"`

	// 血型
	Blood string `json:"blood,omitempty"`

	// 最高学历
	Degree string `json:"degree,omitempty"`

	// 用户ID
	// Required: true
	Euid *string `json:"euid"`

	// 性别
	Gender int64 `json:"gender,omitempty"`

	// 家乡
	HomeArea string `json:"home_area,omitempty"`

	// 兴趣爱好
	Interest string `json:"interest,omitempty"`

	// 婚姻状况
	Marriage string `json:"marriage,omitempty"`

	// 用户昵称
	NickName string `json:"nick_name,omitempty"`

	// 现居城市
	NowArea string `json:"now_area,omitempty"`

	// 职业信息
	Profession string `json:"profession,omitempty"`

	// 个人简介
	Resume string `json:"resume,omitempty"`

	// 目前月薪
	Salary string `json:"salary,omitempty"`

	// 毕业学校
	School string `json:"school,omitempty"`

	// 体型
	Shape string `json:"shape,omitempty"`

	// 身高(cm)
	Stature string `json:"stature,omitempty"`

	// 最后一次修改时间
	UpdateAt int64 `json:"update_at,omitempty"`

	// 体重(kg)
	Weight string `json:"weight,omitempty"`
}

// Validate validates this user info
func (m *UserInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEuid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserInfo) validateEuid(formats strfmt.Registry) error {

	if err := validate.Required("euid", "body", m.Euid); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserInfo) UnmarshalBinary(b []byte) error {
	var res UserInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
